In [1]:
LSEG_CONFIG_PATH = "S:/campaignfinance/config"
import os
os.environ.setdefault("LD_LIB_CONFIG_PATH", str(LSEG_CONFIG_PATH))
import lseg.data as ld
from lseg.data.content import search

In [2]:
ld.open_session()

In [ ]:
query = "5053504265"
response = search.Definition(
    query,
    view=search.Views.ORGANISATIONS,
).get_data()

In [16]:
response.data.df

  BusinessEntity                        DocumentTitle          PI
0           ORGS       America Votes, Private Company  5046267308
1           ORGS  Voting for America, Private Company  5087077535

In [1]:
import polars as pl

In [27]:
DATA_PATH = "S:/campaignfinance/data/processed/fec/firm_pac_donor_profiles_sample_aliasfix/audit/"

In [28]:
a = pl.read_parquet(f"{DATA_PATH}exclusions/cycle_2004/individual_2004_company_employee_non_pac.parquet")
b = pl.read_parquet(f"{DATA_PATH}exclusions/cycle_2004/individual_2004_firm_pac_donor.parquet")

In [29]:
c = pl.read_parquet(f"{DATA_PATH}matched_raw_rows/cycle_2004/individual_2004_firm_pac_donor.parquet")

In [78]:
d = pl.read_parquet(f"{DATA_PATH}person_index/cycle_2004.parquet")

In [31]:
e = pl.read_parquet(f"{DATA_PATH}review_matches/cycle_2004/individual_2004_company_employee_non_pac.parquet")
f = pl.read_parquet(f"{DATA_PATH}review_matches/cycle_2004/individual_2004_firm_pac_donor.parquet")

In [38]:
g = pl.read_parquet("S:/campaignfinance/data/processed/fec/firm_pac_donor_profiles_sample_aliasfix/linked_contributions/cycle_2004/individual_2004_company_employee_non_pac.parquet")
h = pl.read_parquet("S:/campaignfinance/data/processed/fec/firm_pac_donor_profiles_sample_aliasfix/linked_contributions/cycle_2004/individual_2004_firm_pac_donor.parquet")

In [79]:
d

shape: (36_302, 20)
┌───────┬────────────┬────────────┬───────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ cycle ┆ firm_id    ┆ person_com ┆ last_name ┆ … ┆ is_family_ ┆ is_exclud ┆ firm_pac_ ┆ firm_pac_ │
│ ---   ┆ ---        ┆ pany_cycle ┆ ---       ┆   ┆ like       ┆ ed_profil ┆ contribut ┆ contribut │
│ i64   ┆ str        ┆ _id        ┆ str       ┆   ┆ ---        ┆ e         ┆ ion_count ┆ ion_amoun │
│       ┆            ┆ ---        ┆           ┆   ┆ bool       ┆ ---       ┆ ---       ┆ t         │
│       ┆            ┆ str        ┆           ┆   ┆            ┆ bool      ┆ u32       ┆ ---       │
│       ┆            ┆            ┆           ┆   ┆            ┆           ┆           ┆ f64       │
╞═══════╪════════════╪════════════╪═══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2004  ┆ ric:PPG.N  ┆ ric:PPG.N| ┆ maskrey   ┆ … ┆ false      ┆ true      ┆ 1         ┆ 500.0     │
│       ┆            ┆ maskrey|ju ┆           ┆   ┆            ┆           ┆           ┆           │
│       ┆            ┆ dith       ┆           ┆   ┆            ┆           ┆           ┆           │
│ 2004  ┆ permid:500 ┆ permid:500 ┆ miller    ┆ … ┆ null       ┆ null      ┆ 1         ┆ 1100.0    │
│       ┆ 0235959    ┆ 0235959|mi ┆           ┆   ┆            ┆           ┆           ┆           │
│       ┆            ┆ ller|maria ┆           ┆   ┆            ┆           ┆           ┆           │
│ 2004  ┆ ric:PFE.N  ┆ ric:PFE.N| ┆ gorrio    ┆ … ┆ false      ┆ false     ┆ 1         ┆ 500.0     │
│       ┆            ┆ gorrio|car ┆           ┆   ┆            ┆           ┆           ┆           │
│       ┆            ┆ los        ┆           ┆   ┆            ┆           ┆           ┆           │
│ 2004  ┆ permid:429 ┆ permid:429 ┆ abbott    ┆ … ┆ false      ┆ false     ┆ 19        ┆ 3800.0    │
│       ┆ 5903541    ┆ 5903541|ab ┆           ┆   ┆            ┆           ┆           ┆           │
│       ┆            ┆ bott|hersc ┆           ┆   ┆            ┆           ┆           ┆           │
│       ┆            ┆ …          ┆           ┆   ┆            ┆           ┆           ┆           │
│ 2004  ┆ ric:AXP.N  ┆ ric:AXP.N| ┆ belt      ┆ … ┆ false      ┆ false     ┆ 1         ┆ 750.0     │
│       ┆            ┆ belt|jan   ┆           ┆   ┆            ┆           ┆           ┆           │
│ …     ┆ …          ┆ …          ┆ …         ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2004  ┆ ric:WEN.O  ┆ ric:WEN.O| ┆ richards  ┆ … ┆ false      ┆ false     ┆ 2         ┆ 1300.0    │
│       ┆            ┆ richards|t ┆           ┆   ┆            ┆           ┆           ┆           │
│       ┆            ┆ roy        ┆           ┆   ┆            ┆           ┆           ┆           │
│ 2004  ┆ permid:429 ┆ permid:429 ┆ kuehr     ┆ … ┆ false      ┆ true      ┆ 1         ┆ 325.0     │
│       ┆ 5905164    ┆ 5905164|ku ┆           ┆   ┆            ┆           ┆           ┆           │
│       ┆            ┆ ehr|jeffre ┆           ┆   ┆            ┆           ┆           ┆           │
│       ┆            ┆ …          ┆           ┆   ┆            ┆           ┆           ┆           │
│ 2004  ┆ ric:FHN.N  ┆ ric:FHN.N| ┆ ritcheson ┆ … ┆ null       ┆ null      ┆ 1         ┆ 500.0     │
│       ┆            ┆ ritcheson| ┆           ┆   ┆            ┆           ┆           ┆           │
│       ┆            ┆ donald     ┆           ┆   ┆            ┆           ┆           ┆           │
│ 2004  ┆ ric:UPS.N  ┆ ric:UPS.N| ┆ margrave  ┆ … ┆ false      ┆ false     ┆ 1         ┆ 210.0     │
│       ┆            ┆ margrave|w ┆           ┆   ┆            ┆           ┆           ┆           │
│       ┆            ┆ illiam     ┆           ┆   ┆            ┆           ┆           ┆           │
│ 2004  ┆ permid:429 ┆ permid:429 ┆ gillespie ┆ … ┆ false      ┆ false     ┆ 1         ┆ 5000.0    │
│       ┆ 5908473    ┆ 5908473|gi ┆           ┆   ┆            ┆           ┆           ┆           │
│       ┆            ┆ llespie|th ┆           ┆   ┆            ┆           ┆           ┆           │
│       ┆            ┆ …          ┆           ┆   ┆            ┆           ┆           ┆           │
└───────┴────────────┴────────────┴───────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [22]:
a.filter(pl.col("NAME") == "ROBY, ELIZABETH")

shape: (12, 38)
┌───────┬────────────┬────────────┬────────────┬───┬────────────┬──────────┬───────────┬───────────┐
│ cycle ┆ source_fil ┆ cohort     ┆ person_com ┆ … ┆ TRANSACTIO ┆ OTHER_ID ┆ TRAN_ID   ┆ SUB_ID    │
│ ---   ┆ e          ┆ ---        ┆ pany_cycle ┆   ┆ N_TP       ┆ ---      ┆ ---       ┆ ---       │
│ i64   ┆ ---        ┆ str        ┆ _id        ┆   ┆ ---        ┆ str      ┆ str       ┆ str       │
│       ┆ str        ┆            ┆ ---        ┆   ┆ str        ┆          ┆           ┆           │
│       ┆            ┆            ┆ str        ┆   ┆            ┆          ┆           ┆           │
╞═══════╪════════════╪════════════╪════════════╪═══╪════════════╪══════════╪═══════════╪═══════════╡
│ 2004  ┆ data\raw\f ┆ company_em ┆ permid:500 ┆ … ┆ 15         ┆ null     ┆ 041520034 ┆ 404162003 │
│       ┆ ec_bulk\co ┆ ployee_non ┆ 0480830|ro ┆   ┆            ┆          ┆ 5C1322222 ┆ 103083026 │
│       ┆ ntribution ┆ _pac       ┆ by|elizabe ┆   ┆            ┆          ┆           ┆ 4         │
│       ┆ …          ┆            ┆ …          ┆   ┆            ┆          ┆           ┆           │
│ 2004  ┆ data\raw\f ┆ company_em ┆ permid:501 ┆ … ┆ 15         ┆ null     ┆ 041520034 ┆ 404162003 │
│       ┆ ec_bulk\co ┆ ployee_non ┆ 1489569|ro ┆   ┆            ┆          ┆ 5C1322222 ┆ 103083026 │
│       ┆ ntribution ┆ _pac       ┆ by|elizabe ┆   ┆            ┆          ┆           ┆ 4         │
│       ┆ …          ┆            ┆ …          ┆   ┆            ┆          ┆           ┆           │
│ 2004  ┆ data\raw\f ┆ company_em ┆ ric:AEE.N| ┆ … ┆ 15         ┆ null     ┆ 041520034 ┆ 404162003 │
│       ┆ ec_bulk\co ┆ ployee_non ┆ roby|eliza ┆   ┆            ┆          ┆ 5C1322222 ┆ 103083026 │
│       ┆ ntribution ┆ _pac       ┆ beth       ┆   ┆            ┆          ┆           ┆ 4         │
│       ┆ …          ┆            ┆            ┆   ┆            ┆          ┆           ┆           │
│ 2004  ┆ data\raw\f ┆ company_em ┆ ric:AEE.N| ┆ … ┆ 15         ┆ null     ┆ 101420041 ┆ 410162004 │
│       ┆ ec_bulk\co ┆ ployee_non ┆ roby|eliza ┆   ┆            ┆          ┆ 3C14323   ┆ 104338118 │
│       ┆ ntribution ┆ _pac       ┆ beth       ┆   ┆            ┆          ┆           ┆ 8         │
│       ┆ …          ┆            ┆            ┆   ┆            ┆          ┆           ┆           │
│ 2004  ┆ data\raw\f ┆ company_em ┆ permid:501 ┆ … ┆ 15         ┆ null     ┆ 101420041 ┆ 410162004 │
│       ┆ ec_bulk\co ┆ ployee_non ┆ 1489569|ro ┆   ┆            ┆          ┆ 3C14323   ┆ 104338118 │
│       ┆ ntribution ┆ _pac       ┆ by|elizabe ┆   ┆            ┆          ┆           ┆ 8         │
│       ┆ …          ┆            ┆ …          ┆   ┆            ┆          ┆           ┆           │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …        ┆ …         ┆ …         │
│ 2004  ┆ data\raw\f ┆ company_em ┆ permid:500 ┆ … ┆ 15         ┆ null     ┆ 101420041 ┆ 410162004 │
│       ┆ ec_bulk\co ┆ ployee_non ┆ 0650547|ro ┆   ┆            ┆          ┆ 3C14323   ┆ 104338118 │
│       ┆ ntribution ┆ _pac       ┆ by|elizabe ┆   ┆            ┆          ┆           ┆ 8         │
│       ┆ …          ┆            ┆ …          ┆   ┆            ┆          ┆           ┆           │
│ 2004  ┆ data\raw\f ┆ company_em ┆ permid:429 ┆ … ┆ 15         ┆ null     ┆ 101420041 ┆ 410162004 │
│       ┆ ec_bulk\co ┆ ployee_non ┆ 6569313|ro ┆   ┆            ┆          ┆ 3C14323   ┆ 104338118 │
│       ┆ ntribution ┆ _pac       ┆ by|elizabe ┆   ┆            ┆          ┆           ┆ 8         │
│       ┆ …          ┆            ┆ …          ┆   ┆            ┆          ┆           ┆           │
│ 2004  ┆ data\raw\f ┆ company_em ┆ permid:429 ┆ … ┆ 15         ┆ null     ┆ 041520034 ┆ 404162003 │
│       ┆ ec_bulk\co ┆ ployee_non ┆ 6569313|ro ┆   ┆            ┆          ┆ 5C1322222 ┆ 103083026 │
│       ┆ ntribution ┆ _pac       ┆ by|elizabe ┆   ┆            ┆          ┆           ┆ 4         │
│       ┆ …          ┆            ┆ …          ┆   ┆            ┆          ┆           ┆           │
│ 2004  ┆ data\raw\f ┆ company_em ┆ permid:500 ┆ … ┆ 15         ┆ null     ┆ 101420041 ┆ 410162004 │
│       ┆ ec_bulk\co ┆ ployee_non ┆ 0480830|ro ┆   ┆            ┆          ┆ 3C14323   ┆ 104338118 │
│       ┆ ntribution ┆ _pac       ┆ by|elizabe ┆   ┆            ┆          ┆           ┆ 8         │
│       ┆ …          ┆            ┆ …          ┆   ┆            ┆          ┆           ┆           │
│ 2004  ┆ data\raw\f ┆ company_em ┆ permid:500 ┆ … ┆ 15         ┆ null     ┆ 041520034 ┆ 404162003 │
│       ┆ ec_bulk\co ┆ ployee_non ┆ 0650547|ro ┆   ┆            ┆          ┆ 5C1322222 ┆ 103083026 │
│       ┆ ntribution ┆ _pac       ┆ by|elizabe ┆   ┆            ┆          ┆           ┆ 4         │
│       ┆ …          ┆            ┆ …          ┆   ┆            ┆          ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴────────────┴──────────┴───────────┴───────────┘

In [ ]:
i = pl.read_parquet("S:/campaignfinance/data/processed/fec/individual_to_firm_pac_contributions/cycle_2004/individual_2004.parquet")

FileNotFoundError: The system cannot find the file specified. (os error 2): ...ta/processed/fec/individual_to_firm_pac_contributions/cycle_2004/individual_2018.parquet (set POLARS_VERBOSE=1 to see full path)

This error occurred with the following context stack:
	[1] 'parquet scan'
	[2] 'sink'

In [53]:
g.filter((pl.col("NAME") == "EVANS, DWIGHT H"))

shape: (0, 38)
┌───────┬─────────────┬────────┬────────────────┬───┬────────────────┬──────────┬─────────┬────────┐
│ cycle ┆ source_file ┆ cohort ┆ person_company ┆ … ┆ TRANSACTION_TP ┆ OTHER_ID ┆ TRAN_ID ┆ SUB_ID │
│ ---   ┆ ---         ┆ ---    ┆ _cycle_id      ┆   ┆ ---            ┆ ---      ┆ ---     ┆ ---    │
│ i64   ┆ str         ┆ str    ┆ ---            ┆   ┆ str            ┆ str      ┆ str     ┆ str    │
│       ┆             ┆        ┆ str            ┆   ┆                ┆          ┆         ┆        │
╞═══════╪═════════════╪════════╪════════════════╪═══╪════════════════╪══════════╪═════════╪════════╡
└───────┴─────────────┴────────┴────────────────┴───┴────────────────┴──────────┴─────────┴────────┘

In [89]:
i.filter(pl.col("CMTE_ID") == "C00000042")

shape: (5, 22)
┌───────────┬───────────┬────────┬─────────────┬───┬─────────┬───────────┬────────────┬────────────┐
│ CMTE_ID   ┆ AMNDT_IND ┆ RPT_TP ┆ TRANSACTION ┆ … ┆ MEMO_CD ┆ MEMO_TEXT ┆ SUB_ID     ┆ SOURCE_CYC │
│ ---       ┆ ---       ┆ ---    ┆ _PGI        ┆   ┆ ---     ┆ ---       ┆ ---        ┆ LE         │
│ str       ┆ str       ┆ str    ┆ ---         ┆   ┆ str     ┆ str       ┆ str        ┆ ---        │
│           ┆           ┆        ┆ str         ┆   ┆         ┆           ┆            ┆ i32        │
╞═══════════╪═══════════╪════════╪═════════════╪═══╪═════════╪═══════════╪════════════╪════════════╡
│ C00000042 ┆ N         ┆ MY     ┆ null        ┆ … ┆ null    ┆ null      ┆ 4073120031 ┆ 2004       │
│           ┆           ┆        ┆             ┆   ┆         ┆           ┆ 034034347  ┆            │
│ C00000042 ┆ N         ┆ YE     ┆ null        ┆ … ┆ null    ┆ null      ┆ 4011420041 ┆ 2004       │
│           ┆           ┆        ┆             ┆   ┆         ┆           ┆ 034657258  ┆            │
│ C00000042 ┆ N         ┆ Q1     ┆ null        ┆ … ┆ null    ┆ null      ┆ 4040620041 ┆ 2004       │
│           ┆           ┆        ┆             ┆   ┆         ┆           ┆ 037047925  ┆            │
│ C00000042 ┆ N         ┆ Q3     ┆ null        ┆ … ┆ null    ┆ null      ┆ 4101520041 ┆ 2004       │
│           ┆           ┆        ┆             ┆   ┆         ┆           ┆ 043252126  ┆            │
│ C00000042 ┆ A         ┆ 30G    ┆ null        ┆ … ┆ null    ┆ null      ┆ 4021420061 ┆ 2004       │
│           ┆           ┆        ┆             ┆   ┆         ┆           ┆ 064170007  ┆            │
└───────────┴───────────┴────────┴─────────────┴───┴─────────┴───────────┴────────────┴────────────┘

In [26]:
data = pl.scan_csv("E:/dime_recipients_1979_2024.csv", 
    schema_overrides = {"total.disbursements": pl.Float64,
                        "ICPSR": pl.String,
                        "ICPSR2": pl.String,
                        "ind.exp.support": pl.Float64,
                        "total.receipts": pl.Float64,
                        "total.indiv.contribs": pl.Float64,
                        "total.unitemized": pl.Float64,
                        "total.pac.contribs": pl.Float64,
                        "total.party.contribs": pl.Float64,
                        "ind.exp.oppose": pl.Float64,
                        "total.contribs.from.candidate": pl.Float64,
                        "party": pl.String,
                        "party.orig": pl.String})

In [3]:
data = data.filter(pl.col("seat") == "federal:committee").collect()

In [4]:
data.write_parquet("E:/dime_recipients.parquet")

In [11]:
data = data.collect()

In [31]:
data.head().collect()

shape: (5, 64)
┌──────────┬───────┬─────────┬────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ election ┆ cycle ┆ fecyear ┆ bonica.rid ┆ … ┆ nimsp.candi ┆ nimsp.dist ┆ nimsp.offi ┆ nimsp.cand │
│ ---      ┆ ---   ┆ ---     ┆ ---        ┆   ┆ date.ICO.co ┆ rict       ┆ ce         ┆ idate.stat │
│ str      ┆ i64   ┆ i64     ┆ str        ┆   ┆ de          ┆ ---        ┆ ---        ┆ us         │
│          ┆       ┆         ┆            ┆   ┆ ---         ┆ str        ┆ str        ┆ ---        │
│          ┆       ┆         ┆            ┆   ┆ str         ┆            ┆            ┆ str        │
╞══════════╪═══════╪═════════╪════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ fd1980   ┆ 1980  ┆ 1980    ┆ cand2      ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ fd1982   ┆ 1982  ┆ 1982    ┆ cand2      ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ fd1984   ┆ 1984  ┆ 1984    ┆ cand2      ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ fd1986   ┆ 1986  ┆ 1986    ┆ cand2      ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ fd1988   ┆ 1988  ┆ 1988    ┆ cand2      ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
└──────────┴───────┴─────────┴────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [30]:
data.filter(pl.col("bonica.rid") == "comm8716").collect()

shape: (0, 64)
┌──────────┬───────┬─────────┬────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ election ┆ cycle ┆ fecyear ┆ bonica.rid ┆ … ┆ nimsp.candi ┆ nimsp.dist ┆ nimsp.offi ┆ nimsp.cand │
│ ---      ┆ ---   ┆ ---     ┆ ---        ┆   ┆ date.ICO.co ┆ rict       ┆ ce         ┆ idate.stat │
│ str      ┆ i64   ┆ i64     ┆ str        ┆   ┆ de          ┆ ---        ┆ ---        ┆ us         │
│          ┆       ┆         ┆            ┆   ┆ ---         ┆ str        ┆ str        ┆ ---        │
│          ┆       ┆         ┆            ┆   ┆ str         ┆            ┆            ┆ str        │
╞══════════╪═══════╪═════════╪════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
└──────────┴───────┴─────────┴────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [21]:
contrib_2004 = pl.scan_parquet("E:/individual_contribution_2004.parquet")

In [40]:
contrib_2004.filter(pl.col("bonica.rid") == "comm19415").collect()

shape: (76, 32)
┌───────┬────────────┬────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ cycle ┆ transactio ┆ amount ┆ date       ┆ … ┆ contributo ┆ censustrac ┆ efec.org.o ┆ efec.comid │
│ ---   ┆ n.type     ┆ ---    ┆ ---        ┆   ┆ r.district ┆ t          ┆ rig        ┆ .orig      │
│ i64   ┆ ---        ┆ f64    ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│       ┆ str        ┆        ┆            ┆   ┆ str        ┆ i64        ┆ str        ┆ str        │
╞═══════╪════════════╪════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2004  ┆ 18K        ┆ 1000.0 ┆ 2004-04-30 ┆ … ┆ VA08       ┆ 5101310170 ┆ null       ┆ null       │
│       ┆            ┆        ┆            ┆   ┆            ┆ 1          ┆            ┆            │
│ 2004  ┆ 15         ┆ 4200.0 ┆ 2004-04-14 ┆ … ┆ FL06       ┆ 1200100180 ┆ null       ┆ null       │
│       ┆            ┆        ┆            ┆   ┆            ┆ 6          ┆            ┆            │
│ 2004  ┆ 15         ┆ 500.0  ┆ 2003-04-04 ┆ … ┆ GA10       ┆ 1323796010 ┆ null       ┆ null       │
│       ┆            ┆        ┆            ┆   ┆            ┆ 2          ┆            ┆            │
│ 2004  ┆ 15         ┆ 350.0  ┆ 2003-04-10 ┆ … ┆ FL02       ┆ 1206796020 ┆ null       ┆ null       │
│       ┆            ┆        ┆            ┆   ┆            ┆ 0          ┆            ┆            │
│ 2004  ┆ 15         ┆ 1260.0 ┆ 2003-08-28 ┆ … ┆ FL06       ┆ 1204195010 ┆ null       ┆ null       │
│       ┆            ┆        ┆            ┆   ┆            ┆ 0          ┆            ┆            │
│ …     ┆ …          ┆ …      ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2004  ┆ 15         ┆ 418.6  ┆ 2003-03-21 ┆ … ┆ AL07       ┆ 1091973000 ┆ null       ┆ null       │
│ 2004  ┆ 15         ┆ 210.0  ┆ 2004-04-01 ┆ … ┆ FL06       ┆ 1201903120 ┆ null       ┆ null       │
│       ┆            ┆        ┆            ┆   ┆            ┆ 0          ┆            ┆            │
│ 2004  ┆ 15         ┆ 300.0  ┆ 2004-06-28 ┆ … ┆ FL06       ┆ 1208300090 ┆ null       ┆ null       │
│       ┆            ┆        ┆            ┆   ┆            ┆ 2          ┆            ┆            │
│ 2004  ┆ 15         ┆ 535.0  ┆ 2003-05-23 ┆ … ┆ FL16       ┆ 1205596020 ┆ null       ┆ null       │
│       ┆            ┆        ┆            ┆   ┆            ┆ 0          ┆            ┆            │
│ 2004  ┆ 15         ┆ 280.0  ┆ 2003-03-20 ┆ … ┆ FL02       ┆ 1206321030 ┆ null       ┆ null       │
│       ┆            ┆        ┆            ┆   ┆            ┆ 0          ┆            ┆            │
└───────┴────────────┴────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [42]:
committees = contrib_2004.filter(pl.col("bonica.rid").str.contains("comm")).select(["recipient.name", "bonica.rid"]).unique().collect()

In [43]:
cpac = pl.read_csv("S:/campaignfinance/data/raw/fec_bulk/cpac/corporate_pacs_list.csv")

In [53]:
cpac_2004 = cpac.filter(pl.col("YEAR") == 2004)
merged = cpac_2004.join(committees, left_on = "CMTE_NM", right_on = "recipient.name", how = "left")

In [63]:
merged.item(1, "CMTE_NM")

'HALLMARK POLITICAL ACTION COMMITTEE-FEDERAL HALLPAC-FEDERAL'

In [69]:
committees.filter(pl.col("recipient.name").str.contains("METROPOLITAN NATIONAL BANK"))

shape: (0, 2)
┌────────────────┬────────────┐
│ recipient.name ┆ bonica.rid │
│ ---            ┆ ---        │
│ str            ┆ str        │
╞════════════════╪════════════╡
└────────────────┴────────────┘

In [64]:
merged

shape: (1_760, 5)
┌───────────┬──────┬─────────────────────────────────┬────────────────────────────────┬────────────┐
│ CMTE_ID   ┆ YEAR ┆ CMTE_NM                         ┆ CONNECTED_ORG_NM               ┆ bonica.rid │
│ ---       ┆ ---  ┆ ---                             ┆ ---                            ┆ ---        │
│ str       ┆ i64  ┆ str                             ┆ str                            ┆ str        │
╞═══════════╪══════╪═════════════════════════════════╪════════════════════════════════╪════════════╡
│ C00000042 ┆ 2004 ┆ ILLINOIS TOOL WORKS FOR BETTER… ┆ ILLINOIS TOOL WORKS INC        ┆ comm6886   │
│ C00000059 ┆ 2004 ┆ HALLMARK POLITICAL ACTION COMM… ┆ HALLMARK CARDS INCORPORATED    ┆ null       │
│ C00001289 ┆ 2004 ┆ UNION OIL (UNOCAL) POLITICAL A… ┆ UNION OIL CO. OF               ┆ comm6918   │
│           ┆      ┆                                 ┆ CALIFORNIA/DB…                 ┆            │
│ C00001776 ┆ 2004 ┆ NEW MEXICO MEDICAL SOCIETY POL… ┆ New Mexico Medical Society     ┆ null       │
│ C00002790 ┆ 2004 ┆ OLIN CORPORATION GOOD GOVERNME… ┆ OLIN CORPORATION               ┆ comm6971   │
│ …         ┆ …    ┆ …                               ┆ …                              ┆ …          │
│ C00408344 ┆ 2004 ┆ SAN BERNARDINO COUNTY SAFETY E… ┆ SAN BERNARDINO COUNTY SAFETY   ┆ null       │
│           ┆      ┆                                 ┆ E…                             ┆            │
│ C00408492 ┆ 2004 ┆ METROPOLITAN NATIONAL BANK POL… ┆ METROPOLITAN NATIONAL BANK     ┆ null       │
│ C00408500 ┆ 2004 ┆ TELAPEX INC PAC                 ┆ TELAPEX INC                    ┆ null       │
│ C00411454 ┆ 2004 ┆ FLIR SYSTEMS INC EMPLOYEES' PO… ┆ FLIR SYSTEMS INC               ┆ comm21669  │
│ C00411454 ┆ 2004 ┆ FLIR SYSTEMS INC EMPLOYEES' PO… ┆ FLIR SYSTEMS INC               ┆ comm19190  │
└───────────┴──────┴─────────────────────────────────┴────────────────────────────────┴────────────┘

In [8]:
profile = pl.read_parquet("E:/dime_recipients.parquet")
cpac = pl.read_csv("S:/campaignfinance/data/processed/fec/corporate_pac_firm_matches.csv")

In [12]:
profile = profile.select(["cycle", "FEC.ID", "bonica.rid", "recipient.cfscore", "num.givers",
                          "num.givers.total", "total.receipts", "total.disbursements", "total.indiv.contribs",
                          "total.unitemized", "total.pac.contribs", "total.party.contribs",
                          "ind.exp.support", "ind.exp.oppose"])

In [25]:
profile.filter(pl.col("bonica.rid") == "comm6886")

shape: (0, 14)
┌───────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ cycle ┆ FEC.ID ┆ bonica.rid ┆ recipient. ┆ … ┆ total.pac. ┆ total.part ┆ ind.exp.su ┆ ind.exp.op │
│ ---   ┆ ---    ┆ ---        ┆ cfscore    ┆   ┆ contribs   ┆ y.contribs ┆ pport      ┆ pose       │
│ i64   ┆ str    ┆ str        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│       ┆        ┆            ┆ f64        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞═══════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
└───────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [17]:
data = cpac.join(profile, left_on = ["cmte_id", "year"], right_on = ["FEC.ID", "cycle"], how = "left")

In [18]:
data

shape: (18_739, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cmte_id   ┆ cmte_nm   ┆ connected ┆ corporati ┆ … ┆ total.pac ┆ total.par ┆ ind.exp.s ┆ ind.exp. │
│ ---       ┆ ---       ┆ _org_nm   ┆ on        ┆   ┆ .contribs ┆ ty.contri ┆ upport    ┆ oppose   │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ bs        ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ C00000042 ┆ illinois  ┆ illinois  ┆ ILLINOIS  ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ tool      ┆ tool      ┆ TOOL      ┆   ┆           ┆           ┆           ┆          │
│           ┆ works for ┆ works     ┆ WORKS     ┆   ┆           ┆           ┆           ┆          │
│           ┆ better…   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ C00000042 ┆ illinois  ┆ illinois  ┆ ILLINOIS  ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ tool      ┆ tool      ┆ TOOL      ┆   ┆           ┆           ┆           ┆          │
│           ┆ works for ┆ works     ┆ WORKS     ┆   ┆           ┆           ┆           ┆          │
│           ┆ better…   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ C00000042 ┆ illinois  ┆ illinois  ┆ ILLINOIS  ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ tool      ┆ tool      ┆ TOOL      ┆   ┆           ┆           ┆           ┆          │
│           ┆ works for ┆ works     ┆ WORKS     ┆   ┆           ┆           ┆           ┆          │
│           ┆ better…   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ C00000042 ┆ illinois  ┆ illinois  ┆ ILLINOIS  ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ tool      ┆ tool      ┆ TOOL      ┆   ┆           ┆           ┆           ┆          │
│           ┆ works for ┆ works     ┆ WORKS     ┆   ┆           ┆           ┆           ┆          │
│           ┆ better…   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ C00000042 ┆ illinois  ┆ illinois  ┆ ILLINOIS  ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ tool      ┆ tool      ┆ TOOL      ┆   ┆           ┆           ┆           ┆          │
│           ┆ works for ┆ works     ┆ WORKS     ┆   ┆           ┆           ┆           ┆          │
│           ┆ better…   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ C00893925 ┆ civitas   ┆ civitas   ┆ CIVITAS   ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ resources ┆ resources ┆ RESOURCES ┆   ┆           ┆           ┆           ┆          │
│ C00893933 ┆ fuse inte ┆ fuse inte ┆ FUSE INTE ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ gration   ┆ gration   ┆ GRATION   ┆   ┆           ┆           ┆           ┆          │
│           ┆ mission   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ first     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ C00894055 ┆ circle    ┆ circle    ┆ CIRCLE    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ internet  ┆ internet  ┆ INTERNET  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ GROUP     ┆   ┆           ┆           ┆           ┆          │
│ C00894196 ┆ fluence   ┆ fluence   ┆ FLUENCE   ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ energy    ┆ energy    ┆ ENERGY    ┆   ┆           ┆           ┆           ┆          │
│           ┆ aka       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ fluence   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ C00894345 ┆ banc of   ┆ banc of   ┆ BANC OF   ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ californi ┆ californi ┆ CALIFORNI ┆   ┆           ┆           ┆           ┆          │
│           ┆ a         ┆ a         ┆ A         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ POLITICAL ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ A…        ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [34]:
data = pl.scan_csv("E:/dime_contributors_1979_2024.csv")

In [35]:
data.head().collect()

shape: (5, 43)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ bonica.ci ┆ contribut ┆ num.disti ┆ most.rece ┆ … ┆ amount.20 ┆ amount.20 ┆ amount.20 ┆ amount.2 │
│ d         ┆ or.type   ┆ nct       ┆ nt.contri ┆   ┆ 18        ┆ 20        ┆ 22        ┆ 024      │
│ ---       ┆ ---       ┆ ---       ┆ butor.nam ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ str       ┆ i64       ┆ e         ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64      │
│           ┆           ┆           ┆ ---       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ C         ┆ 364       ┆ laborers  ┆ … ┆ 319579    ┆ 576850    ┆ 219700    ┆ 0        │
│           ┆           ┆           ┆ district  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ council   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ of m…     ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ C         ┆ 11        ┆ 13th      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆           ┆           ┆ colony    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ leadershi ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ p cmte    ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ I         ┆ 16        ┆ jay,      ┆ … ┆ 1750      ┆ 0         ┆ 250       ┆ 1000     │
│           ┆           ┆           ┆ william   ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ C         ┆ 108       ┆ acxiom    ┆ … ┆ 32500     ┆ 1000      ┆ 0         ┆ 27000    │
│           ┆           ┆           ┆ corp      ┆   ┆           ┆           ┆           ┆          │
│ 6         ┆ C         ┆ 1         ┆ banks     ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆           ┆           ┆ brown inc ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [1]:
import polars as pl

In [22]:
data = pl.scan_parquet("S:/campaignfinance/data/raw/dime/individual_contribution_2018.parquet")

In [23]:
data.filter(pl.col("bonica.rid") == "comm127988").collect()

shape: (870, 32)
┌───────┬────────────┬────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ cycle ┆ transactio ┆ amount ┆ date       ┆ … ┆ contributo ┆ censustrac ┆ efec.org.o ┆ efec.comid │
│ ---   ┆ n.type     ┆ ---    ┆ ---        ┆   ┆ r.district ┆ t          ┆ rig        ┆ .orig      │
│ i64   ┆ ---        ┆ f64    ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│       ┆ str        ┆        ┆            ┆   ┆ str        ┆ i64        ┆ str        ┆ str        │
╞═══════╪════════════╪════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2018  ┆ 15         ┆ 208.0  ┆ 2017-05-15 ┆ … ┆ NY17       ┆ 3611900860 ┆ TELADOC    ┆ C00579359  │
│       ┆            ┆        ┆            ┆   ┆            ┆ 2          ┆ INC        ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ POLITICAL  ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ ACTION C…  ┆            │
│ 2018  ┆ 15         ┆ 25.0   ┆ 2017-05-01 ┆ … ┆ NY17       ┆ 3611900860 ┆ TELADOC    ┆ C00579359  │
│       ┆            ┆        ┆            ┆   ┆            ┆ 2          ┆ INC        ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ POLITICAL  ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ ACTION C…  ┆            │
│ 2018  ┆ 15         ┆ 25.0   ┆ 2017-06-15 ┆ … ┆ NY17       ┆ 3611900860 ┆ TELADOC    ┆ C00579359  │
│       ┆            ┆        ┆            ┆   ┆            ┆ 2          ┆ INC        ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ POLITICAL  ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ ACTION C…  ┆            │
│ 2018  ┆ 15         ┆ 16.0   ┆ 2017-06-01 ┆ … ┆ NY17       ┆ 3611900860 ┆ TELADOC    ┆ C00579359  │
│       ┆            ┆        ┆            ┆   ┆            ┆ 2          ┆ INC        ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ POLITICAL  ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ ACTION C…  ┆            │
│ 2018  ┆ 15         ┆ 21.0   ┆ 2017-06-30 ┆ … ┆ NY17       ┆ 3611900860 ┆ TELADOC    ┆ C00579359  │
│       ┆            ┆        ┆            ┆   ┆            ┆ 2          ┆ INC        ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ POLITICAL  ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ ACTION C…  ┆            │
│ …     ┆ …          ┆ …      ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2018  ┆ 15         ┆ 125.0  ┆ 2018-10-01 ┆ … ┆ NY17       ┆ 3611900860 ┆ TELADOC    ┆ C00579359  │
│       ┆            ┆        ┆            ┆   ┆            ┆ 2          ┆ HEALTH,    ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ INC.       ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ POLITICAL… ┆            │
│ 2018  ┆ 15         ┆ 41.66  ┆ 2018-10-01 ┆ … ┆ NY17       ┆ 3611900860 ┆ TELADOC    ┆ C00579359  │
│       ┆            ┆        ┆            ┆   ┆            ┆ 2          ┆ HEALTH,    ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ INC.       ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ POLITICAL… ┆            │
│ 2018  ┆ 15         ┆ 208.33 ┆ 2018-11-15 ┆ … ┆ NY17       ┆ 3611900860 ┆ TELADOC    ┆ C00579359  │
│       ┆            ┆        ┆            ┆   ┆            ┆ 2          ┆ HEALTH,    ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ INC.       ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ POLITICAL… ┆            │
│ 2018  ┆ 15         ┆ 25.0   ┆ 2018-11-01 ┆ … ┆ NY17       ┆ 3611900860 ┆ TELADOC    ┆ C00579359  │
│       ┆            ┆        ┆            ┆   ┆            ┆ 2          ┆ HEALTH,    ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ INC.       ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ POLITICAL… ┆            │
│ 2018  ┆ 15         ┆ 208.33 ┆ 2018-11-01 ┆ … ┆ NY17       ┆ 3611900860 ┆ TELADOC    ┆ C00579359  │
│       ┆            ┆        ┆            ┆   ┆            ┆ 2          ┆ HEALTH,    ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ INC.       ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ POLITICAL… ┆            │
└───────┴────────────┴────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [19]:
data.filter(pl.col("bonica.rid") == "comm21669").collect()

shape: (8, 32)
┌───────┬────────────┬─────────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ cycle ┆ transactio ┆ amount  ┆ date       ┆ … ┆ contributo ┆ censustrac ┆ efec.org.o ┆ efec.comi │
│ ---   ┆ n.type     ┆ ---     ┆ ---        ┆   ┆ r.district ┆ t          ┆ rig        ┆ d.orig    │
│ i64   ┆ ---        ┆ f64     ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│       ┆ str        ┆         ┆            ┆   ┆ str        ┆ i64        ┆ str        ┆ str       │
╞═══════╪════════════╪═════════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 2004  ┆ 15         ┆ 1400.0  ┆ 2004-12-23 ┆ … ┆ MA05       ┆ 2501736510 ┆ null       ┆ null      │
│       ┆            ┆         ┆            ┆   ┆            ┆ 0          ┆            ┆           │
│ 2004  ┆ 15         ┆ 2500.0  ┆ 2004-10-06 ┆ … ┆ OR05       ┆ 4100502010 ┆ null       ┆ null      │
│       ┆            ┆         ┆            ┆   ┆            ┆ 0          ┆            ┆           │
│ 2004  ┆ 15         ┆ 1458.31 ┆ 2004-12-23 ┆ … ┆ OR01       ┆ 4106703010 ┆ null       ┆ null      │
│       ┆            ┆         ┆            ┆   ┆            ┆ 1          ┆            ┆           │
│ 2004  ┆ 15         ┆ 2000.0  ┆ 2004-10-19 ┆ … ┆ MA09       ┆ 2502141610 ┆ null       ┆ null      │
│       ┆            ┆         ┆            ┆   ┆            ┆ 1          ┆            ┆           │
│ 2004  ┆ 15         ┆ 5000.0  ┆ 2004-11-02 ┆ … ┆ MA06       ┆ 2500921310 ┆ null       ┆ null      │
│       ┆            ┆         ┆            ┆   ┆            ┆ 0          ┆            ┆           │
│ 2004  ┆ 15         ┆ 3000.0  ┆ 2004-10-08 ┆ … ┆ MA07       ┆ 2501735840 ┆ null       ┆ null      │
│       ┆            ┆         ┆            ┆   ┆            ┆ 0          ┆            ┆           │
│ 2004  ┆ 15         ┆ 5000.0  ┆ 2004-10-06 ┆ … ┆ OR01       ┆ 4106703190 ┆ null       ┆ null      │
│       ┆            ┆         ┆            ┆   ┆            ┆ 8          ┆            ┆           │
│ 2004  ┆ 15         ┆ 1458.31 ┆ 2004-12-23 ┆ … ┆ OR05       ┆ 4100502270 ┆ null       ┆ null      │
│       ┆            ┆         ┆            ┆   ┆            ┆ 2          ┆            ┆           │
└───────┴────────────┴─────────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [15]:
subset = data.filter(pl.col("recipient.name").str.to_uppercase() == "J.P. MORGAN CHASE & CO. STATE AND FEDERAL POLITICAL ACTION COMMITTEE").collect()

In [16]:
subset.filter(pl.col("recipient.name") == "j.p. morgan chase & co. state and federal political action committee")

shape: (2, 32)
┌───────┬────────────┬────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ cycle ┆ transactio ┆ amount ┆ date       ┆ … ┆ contributo ┆ censustrac ┆ efec.org.o ┆ efec.comid │
│ ---   ┆ n.type     ┆ ---    ┆ ---        ┆   ┆ r.district ┆ t          ┆ rig        ┆ .orig      │
│ i64   ┆ ---        ┆ f64    ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│       ┆ str        ┆        ┆            ┆   ┆ str        ┆ i64        ┆ str        ┆ str        │
╞═══════╪════════════╪════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2004  ┆ 18K        ┆ 1500.0 ┆ 2003-12-12 ┆ … ┆ DC01       ┆ 1100101070 ┆ null       ┆ null       │
│       ┆            ┆        ┆            ┆   ┆            ┆ 0          ┆            ┆            │
│ 2004  ┆ 18K        ┆ 5000.0 ┆ 2004-05-21 ┆ … ┆ DC01       ┆ 1100101070 ┆ null       ┆ null       │
│       ┆            ┆        ┆            ┆   ┆            ┆ 0          ┆            ┆            │
└───────┴────────────┴────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [17]:
subset.filter(pl.col("contributor.name").str.contains("americans for a republican"))

shape: (2, 32)
┌───────┬────────────┬────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ cycle ┆ transactio ┆ amount ┆ date       ┆ … ┆ contributo ┆ censustrac ┆ efec.org.o ┆ efec.comid │
│ ---   ┆ n.type     ┆ ---    ┆ ---        ┆   ┆ r.district ┆ t          ┆ rig        ┆ .orig      │
│ i64   ┆ ---        ┆ f64    ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│       ┆ str        ┆        ┆            ┆   ┆ str        ┆ i64        ┆ str        ┆ str        │
╞═══════╪════════════╪════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2004  ┆ 18K        ┆ 1500.0 ┆ 2003-12-12 ┆ … ┆ DC01       ┆ 1100101070 ┆ null       ┆ null       │
│       ┆            ┆        ┆            ┆   ┆            ┆ 0          ┆            ┆            │
│ 2004  ┆ 18K        ┆ 5000.0 ┆ 2004-05-21 ┆ … ┆ DC01       ┆ 1100101070 ┆ null       ┆ null       │
│       ┆            ┆        ┆            ┆   ┆            ┆ 0          ┆            ┆            │
└───────┴────────────┴────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [9]:
subset.filter(pl.col("contributor.fname") == "eliza")

shape: (4, 32)
┌───────┬────────────┬────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ cycle ┆ transactio ┆ amount ┆ date       ┆ … ┆ contributo ┆ censustrac ┆ efec.org.o ┆ efec.comid │
│ ---   ┆ n.type     ┆ ---    ┆ ---        ┆   ┆ r.district ┆ t          ┆ rig        ┆ .orig      │
│ i64   ┆ ---        ┆ f64    ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│       ┆ str        ┆        ┆            ┆   ┆ str        ┆ i64        ┆ str        ┆ str        │
╞═══════╪════════════╪════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2024  ┆ 15         ┆ 1028.2 ┆ 2023-04-20 ┆ … ┆ UT03       ┆ 4904396440 ┆ Merrion    ┆ C00815183  │
│       ┆            ┆        ┆            ┆   ┆            ┆ 2          ┆ Oil & Gas  ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ Corporatio ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ n …        ┆            │
│ 2024  ┆ 527        ┆ 1028.0 ┆ 2023-04-20 ┆ … ┆ UT03       ┆ 4904396440 ┆ null       ┆ null       │
│       ┆            ┆        ┆            ┆   ┆            ┆ 2          ┆            ┆            │
│ 2024  ┆ 527        ┆ 1038.0 ┆ 2024-04-11 ┆ … ┆ UT03       ┆ 4904396440 ┆ null       ┆ null       │
│       ┆            ┆        ┆            ┆   ┆            ┆ 2          ┆            ┆            │
│ 2024  ┆ 15         ┆ 1038.6 ┆ 2024-04-11 ┆ … ┆ UT03       ┆ 4904396440 ┆ Merrion    ┆ C00815183  │
│       ┆            ┆        ┆            ┆   ┆            ┆ 2          ┆ Oil & Gas  ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ Corporatio ┆            │
│       ┆            ┆        ┆            ┆   ┆            ┆            ┆ n …        ┆            │
└───────┴────────────┴────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘